### ISSUE TITLE
Changing endpoint URL

### ISSUE THREAD

**Issue by BananaGoldberg** [mkaykisiz/DjangoS3Browser#5]
Hi,

ist there any chance that, the endpoint URL can be changed so I can use a non amazonaws bucket? I always end up with the following Error:

botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://**s3.amazonaws.com**/MYBUCKET?location

Best Regards

Banana

**Comment by mkaykisiz** [comment]
Görebildiğim kadarıyla sorunu çözdün. Lütfen bir çekme isteği açın.

**Comment by mkaykisiz** [comment]
As far as I can see, you solved the problem. Please open a pull request.
